services:
  db:
    image: postgres:17
    container_name: barbearia-db
    environment:
      POSTGRES_USER: barbearia
      POSTGRES_PASSWORD: barbearia
      POSTGRES_DB: barbearia
    ports:
      - "5433:5432"
    volumes:
      - barbearia-dados:/var/lib/postgresql/data

volumes:
  barbearia-dados: